version: 2
jobs:
  build:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: behdad222/android-sdk:v2.0.0
    branches:
      only:
        - master
    steps:
      - checkout
      - run: pluginVersion=$(cat www/tapsell.js | grep "tapsellPluginVersion" | cut -d'=' -f2)
      - run: pluginVersion=${pluginVersion## }
      - run: pluginVersion=${pluginVersion%% }
      - run: npm publish
      - run: curl -XGET http://answers.tapsell.ir/wp-content/plugins/versionAutomation/updateversion.php?key=1234567890&platform=cordovaPlugin&version=$pluginVersion
      - run: git clone https://github.com/tapsellorg/TapsellSDK-CordovaSample.git
      - run: cd TapsellSDK-CordovaSample
      - run: cordova plugin remove tapsell-v3-cordova-plugin
      - run: cordova plugin add tapsell-v3-cordova-plugin
      - run: git add --all
      - run: git config --local user.name "circleCI"
      - run: echo ${SSH_KEY} > ~/.ssh/circleCI
      - run: eval "$(ssh-agent -s)"
      - run: ssh-add -K ~/.ssh/gitlabCI
      - run: git commit -m "updating for sdk cordova version $pluginVersion"
      - run: git push
      - run: cd ..
      - run: rm -rf TapsellSDK-CordovaSample
