version: 2
defaults: &defaults
  docker:
    - image: behdad222/android-sdk:v2.1.1
jobs:
  npmPublish:
      <<: *defaults
      steps:
        - checkout
        - run: npm install
        - run:
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        - run:
            name: Publish package
            command: npm publish

  sampleUpdate:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update sample project
          command: |
            pluginVersion=$(cat www/tapsell.js | grep "var tapsellPluginVersion =" | cut -d'"' -f2)
            echo $pluginVersion
            git clone git@github.com:tapsellorg/TapsellSDK-CordovaSample.git
            cd TapsellSDK-CordovaSample
            cordova plugin remove tapsell-v3-cordova-plugin
            cordova plugin add tapsell-v3-cordova-plugin
            git add --all
            git config --local user.name "circleCI"
            git config --local user.email "technical.tapsell@gmail.com"
            git commit -m "updating for sdk cordova version $pluginVersion"
            git push

  docUpdate:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: update tapsell docs
          command: |
            pluginVersion=$(cat www/tapsell.js | grep "var tapsellPluginVersion =" | cut -d'"' -f2)
            wget http://answers.tapsell.ir/wp-content/plugins/versionAutomation/updateversion.php\?key\=$DOC_TOKEN\&platform\=cordovaPlugin\&version\=$pluginVersion


workflows:
  version: 2
  publish:
    jobs:
      - hold:
          type: approval
          
      - npmPublish:
          requires:
            - hold
            
      - docUpdate:
          requires:
            - npmPublish
            
      - sampleUpdate:
          requires:
            - npmPublish

