version: 2
jobs:
  npmPublish:
      docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
        - image: behdad222/android-sdk:v2.1.1
        
      steps:
        - checkout
        - run:
            command: | 
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              npm publish .


  sampleUpdate:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: behdad222/android-sdk:v2.1.1
      
    steps:
      - checkout
      - run:
          command: |
            pluginVersion=$(cat www/tapsell.js | grep "var tapsellPluginVersion =" | cut -d'"' -f2)
            echo $pluginVersion
            git clone git@github.com:tapsellorg/TapsellSDK-CordovaSample.git
            cd TapsellSDK-CordovaSample
            cordova plugin remove tapsell-v3-cordova-plugin
            cordova plugin add tapsell-v3-cordova-plugin
            git add --all
            git config --local user.name "circleCI"
            git config --local user.email "technical.tapsell@gmail.com"
            git commit -m "updating for sdk cordova version $pluginVersion"
            git push
            
            
  docUpdate:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: behdad222/android-sdk:v2.1.1
      
    steps:
      - checkout
      - run:
          command: |
            pluginVersion=$(cat www/tapsell.js | grep "var tapsellPluginVersion =" | cut -d'"' -f2)
            wget http://answers.tapsell.ir/wp-content/plugins/versionAutomation/updateversion.php\?key\=$DOC_TOKEN\&platform\=cordovaPlugin\&version\=$pluginVersion


workflows:
  version: 2
  publish:
    jobs:
      - hold:
          type: approval
          
      - npmPublish:
          requires:
            - hold
            
      - docUpdate:
          requires:
            - npmPublish
            
      - sampleUpdate:
          requires:
            - npmPublish

