version: 2
jobs:
  publish:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: behdad222/android-sdk:v2.0.0
    steps:
      - checkout
      - run: pluginVersion=$(cat www/tapsell.js | grep "tapsellPluginVersion" | cut -d'=' -f2)
      - run: pluginVersion=${pluginVersion## }
      - run: pluginVersion=${pluginVersion%% }
#      - run: npm publish
#      - run: curl -XGET http://answers.tapsell.ir/wp-content/plugins/versionAutomation/updateversion.php?key=$DOC_KEY&platform=cordovaPlugin&version=$pluginVersion
      - run: git clone git@github.com:tapsellorg/TapsellSDK-CordovaSample.git
      - run: cd TapsellSDK-CordovaSample
      - run: cordova plugin remove tapsell-v3-cordova-plugin
      - run: cordova plugin add tapsell-v3-cordova-plugin
      - run: git add --all
      - run: git config --local user.name "circleCI"
      - run: git config --local user.email "technical.tapsell@gmail.com"
      - run: echo ${SSH_KEY} > ~/.ssh/id_rsa
      - run: cat ~/.ssh/id_rsa
      - run: chmod 0400 ~/.ssh/id_rsa
#      - run: eval "$(ssh-agent -s)"
#      - run: ssh-add ~/.ssh/id_rsa
      - run: git commit -m "updating for sdk cordova version $pluginVersion"
      - run: git push
      - run: cd ..
      - run: rm -rf TapsellSDK-CordovaSample
workflows:
  version: 2
  deploy:
    jobs:
      - hold:
          type: approval
      - publish:
          requires:
            - hold

